# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2c8ad0dcd6f934fcc6326ef11b3f4e45c00e518f34e2087f9a4765dab00b8beb0e89daaf3aa2a143573fceb06889c0b7247556473a5221059008592109905498

test:
  secret_key_base: 722a87803cbc997ee12bb2913725fbf7e1572e25c775403b6f913f11d82fbc9d657e3e75b4b71aa407e085f00c68c48c59f209c313a5e04209d7e224854b242e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
